apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@kingscode.nl
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudDNS:
            project: {{ .Values.general.gcp_project }}
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
