apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: api-secrets
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: api-secrets-{{ .Values.environment }}
