apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: some-website-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    cert-manager.io/cluster-issuer: {{ .Values.general.issuerName }}
spec:
  tls:
    - secretName: {{ .Values.frontend.secretName }}
      hosts:
        - "{{ .Values.frontend.hostUrl }}"
        - "{{ .Values.frontend.hostUrlWildcard }}"
  rules:
    - host: "{{ .Values.frontend.hostUrlWildcard }}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: some-website-frontend
                port:
                  number: 80
